debug

diff --git a/validate-charts/action.yml b/validate-charts/action.yml
--- a/validate-charts/action.yml
+++ b/validate-charts/action.yml
@@ -20,7 +20,7 @@ runs:
         helm lint ${{ inputs.chart-path }} ${{ inputs.extra-args }}
         helm template ${{ inputs.chart-path }} ${{ inputs.extra-args }}
     - name: ensure no trailing spaces in config maps
-      shell: bash
+      shell: bash --noprofile --norc -e {0} # removing pipefail from default for hacking around grep exit code
       run: |
         configmaps=($(find ${{ inputs.chart-path }} -type f -regex '.*\.ya*ml' -exec grep -l "kind: ConfigMap" {} \;))
         COUNTER=0
@@ -28,7 +28,7 @@ runs:
         for yaml in "${configmaps[@]}"
         do
             echo $yaml
-            if ! $(grep -c '\S\s+$' $yaml); then matches=0; else matches=$(grep -c '\S\s+$' $yaml) || true;  fi
+            matches=$(grep -c '\S\s+$' $yaml) | tr a a
             echo $matches
             test $matches -ne 0 && (grep -nE '\S\s+$' $yaml || true) && echo "^^^^^^ in file: $yaml" && echo
         done
